# Generated by Django 3.2.4 on 2021-06-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('column_separator', models.CharField(choices=[(',', 'Comma(,)'), (';', 'Semicolon(;)'), ('|', 'Pipe(|)')], default=',', max_length=30)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")], default='"', max_length=30)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('from_value', models.IntegerField(blank=True)),
                ('to_value', models.IntegerField(blank=True)),
                ('order', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='app.schema')),
            ],
        ),
    ]
