# Generated by Django 3.2.4 on 2021-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Email', 'Email'), ('Phone number', 'Phone number'), ('Job', 'Job'), ('Integer', 'Integer'), ('Company', 'Company')], default='Full name', max_length=20),
        ),
    ]
