# Generated by Django 3.2.4 on 2021-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_column_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='from_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='column',
            name='to_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
