# Generated by Django 3.2.4 on 2021-06-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210610_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='from_value',
            new_name='from',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='to_value',
            new_name='to',
        ),
    ]
