# Generated by Django 3.2.4 on 2021-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_dataset_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Email', 'Email'), ('Phone number', 'Phone number'), ('Job', 'Job'), ('Integer', 'Integer'), ('Company', 'Company')], default='Integer', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
